service: minionless
plugins:
  - serverless-dotenv-plugin

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256

#${file(./config.${opt:stage, 'dev'}.json):CREDS}
functions:
  mailer:
    handler: mailer.handle
    events:
      - http:
          method: POST
          path: mailer
          cors: true